'on':
  push:
    tags:
      - v*
jobs:
  compile:
    name: Compile extension in docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: 'registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest'
          options: '-v ${{ github.workspace }}:/mnt/curl'
          run: |
            bash /mnt/curl/ci/_docker_script.sh
      - name: Zip packages
        run: |
          pwd
          ls -la
          pushd build
          7za a -r sm-neocurl.zip scripting/ plugins/ extensions/
          ls -la
          pwd
          ls -la
          popd
      - name: Release
        uses: softprops/action-gh-release@v1
        if: 'startsWith(github.ref, ''refs/tags/'')'
        with:
          files: |
            ./build/sm-neocurl.zip
